// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBDozPfPEx6Rdp4GxDG0eiG9qL9t4ZNJM',
    appId: '1:33958095411:web:6a3c455bd315597aded146',
    messagingSenderId: '33958095411',
    projectId: 'demo1-acab1',
    authDomain: 'demo1-acab1.firebaseapp.com',
    storageBucket: 'demo1-acab1.appspot.com',
    measurementId: 'G-HY87CF1TCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbntQKaFJ27R9N6Zg6-fn3IGIqsB_9gjg',
    appId: '1:33958095411:android:b78436ccbe718032ded146',
    messagingSenderId: '33958095411',
    projectId: 'demo1-acab1',
    storageBucket: 'demo1-acab1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhiRfCax-s2DeYqxo1JP8HnuX7Y53a514',
    appId: '1:33958095411:ios:aaf3177b50d29c28ded146',
    messagingSenderId: '33958095411',
    projectId: 'demo1-acab1',
    storageBucket: 'demo1-acab1.appspot.com',
    iosBundleId: 'com.example.ecomerce3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhiRfCax-s2DeYqxo1JP8HnuX7Y53a514',
    appId: '1:33958095411:ios:aaf3177b50d29c28ded146',
    messagingSenderId: '33958095411',
    projectId: 'demo1-acab1',
    storageBucket: 'demo1-acab1.appspot.com',
    iosBundleId: 'com.example.ecomerce3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBDozPfPEx6Rdp4GxDG0eiG9qL9t4ZNJM',
    appId: '1:33958095411:web:babb0c320db37fecded146',
    messagingSenderId: '33958095411',
    projectId: 'demo1-acab1',
    authDomain: 'demo1-acab1.firebaseapp.com',
    storageBucket: 'demo1-acab1.appspot.com',
    measurementId: 'G-NY0GT61NJP',
  );
}
